task:
  name: freebsd-x86_64
  freebsd_instance:
    image_family: freebsd-13-0
  environment:
    CIRRUS_CLONE_SUBMODULES: true
    S3_ACCESS_KEY: ENCRYPTED[2f368bef589e43779394e459191eaad2fc4cc50dc36c6f03168a1e8e43897476e8bf596fd4dd0d988bcbab8fa8e171f8]
    S3_SECRET_KEY: ENCRYPTED[45f352473433a1053622a662ce8d57bc7421bce5772c9c5caf4a0e54f63944bd420f71101e014876e038f0c66c134ac2]
    CF_EMAIL: ENCRYPTED[a9f0dcd0ee83fa111c36f092f34b3d5660acafe0d07804d6b6a89bfa70a127ef8305f21089408959c51e23ecd2fd3622]
    CF_TOKEN: ENCRYPTED[4f9f3f7c8603fd32978b825d65f34b06fce8e51bedb4303744c799d21fc38266173a6be5a7a46b5e616573d27c9f6e91]
  install_dependencies_script: |
    pwd
    id
    pkg install -y \
      bash \
      git \
      npm \
      py38-s3cmd
    npm install -g cloudflare-cli@4.2.0
  initialize_credentials_script: |
    (
      echo "[default]"
      echo "access_key = $S3_ACCESS_KEY"
      echo "secret_key = $S3_SECRET_KEY"
    ) > ~/.s3cfg
    (
      echo "defaults:"
      echo "    domain: frida.re"
      echo "    email: $CF_EMAIL"
      echo "    token: $CF_TOKEN"
    ) > ~/.cfcli.yml
  roll_toolchain_script: releng/deps.py roll toolchain freebsd-x86_64 --activate
  roll_sdk_script: releng/deps.py roll sdk freebsd-x86_64
  build_gum_script: make gum
  test_gum_script: make check-gum
  build_core_script: make core
  test_core_script: make check-core
  build_python_script: make python
  test_python_script: make check-python
  build_node_script: make node
  test_node_script: make check-node
  build_tools_script: make tools
  test_tools_script: make check-tools
